#!/usr/bin/perl
#perl script to get a column from a file



#get arguments
if( scalar ( @ARGV ) < 1 )
{
	die "requires minimum 1 arguments:column numbers to take from stdin .\n";
}

$i = 0;
#loop over each column number passed in.
while( @ARGV >= 1 )
{
   #get first argument
   $colNo[$i] = shift;
   $i++;

}
$numColumns = $i;


   #read the file into an array
   while ( $input = <STDIN> ) 
   {

	@inList = split( /\s+/, $input );

	for( $i = 0; $i < $numColumns; $i++ )
	{
	    print $inList[$colNo[$i]]."  ";
	}
	print "\n";
	
   }

